### ISSUE TITLE
Reserved Calendar Events Don't Work

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#120]
Creating an Event on a Calendar at a given date and time with a specific version of an Application doesn't keep that version from being deployed. The only between the version that should be deployed and the one that shouldn't is that the one that shouldn't be deployed has a message in the log tab of the Results window:

Failed to create Target Directory
Exception at line 0: dmtransfer did not execute successfully

Even though the files are deployed.

**Comment by rightker** [comment]
The time on the RE server and target server were off by 45 minutes, so I reset them to be in sync with my laptop in Mountain Time. I set up an Autodeploy to take place at 2 p.m., but nothing happened. I did a manual deploy at 2:10 p.m. and it shows up as having deployed at 3:10 p.m. I'll wait until 3 p.m., I expect the Autodeploy will deploy, but I don't know what's going on.

**Comment by rightker** [comment]
I set up a deploy to go off at 5:00, but it didn't go off until 6:00, and recorded it as having deployed at 5:00.

**Comment by pgibbs-openmake** [comment]
It sounds like the engine and the web interface are running on different time zones - are they both on the same server?

Phil Gibbs

Vice President Engineering / OpenMake Software <http://www.openmakesoftware.com/> / t. +44 (0)113 366 2015 / m. +44 (0)7713 731128
Follow us on: Blog <http://www.openmakesoftware.com/insights/> / Twitter  <http://www.twitter.com/openmake>/ Facebook <https://www.facebook.com/pages/OpenMake-Software/478045172208305> / LinkedIn <http://uk.linkedin.com/in/philgibbstrinem> / YouTube <https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ> /  <https://plus.google.com/114739548678948537118/posts>Google <https://plus.google.com/b/114739548678948537118/114739548678948537118/post>+ / Dynamic DevOps Suite Video <https://www.youtube.com/watch?v=GX36uELDK0I>
Winners of the Jolt Award in Change and Configuration Management

**Comment by rightker** [comment]
Yes they are.

**Comment by rightker** [comment]
I ran another one this a.m. The times in various places are:

Set up in Calendar: 9:00
Time shown as having run on Calendar: 9:00
Time shown in Log tab: 11:00
Actual Mountain Time Zone, my laptop, both RE and target servers: 10:00

**Comment by rightker** [comment]
Set up another autodeploy to run at 2:00 p.m. MDT, which is 8:00 p.m. UTC. The server containing the engine and web server was set to the correct UTC time. I set the deployment up at 10 minutes till 2:00, and it did not allow me to set up anything earlier, so the Calendar was behaving correctly. It didn't run until 3:00 p.m., an hour after it was scheduled to run. The Calendar shows it ran at 2:00 (1400), and the log shows it ran at 10:00 p.m., which is the actual UTC time it ran.

**Comment by pgibbs-openmake** [comment]
There's something odd going on with timezones here - I cannot reproduce this. Attempting a deployment during a reservation of another app is denied as expected. The message about "dmtransfer" is a red herring caused by a deployment failure - it should not be attempting to perform the deployment. Given that things are an hour out on testing, it may be a DST issue.

**Comment by pgibbs-openmake** [comment]
Also, 7.7 also has an "open for business" setting on the environment. This means you can deny ALL deployments unless there's a calendar entry allowing them OR allow all deployments unless there's a calendar entry denying them. That could do with testing!

**Comment by rightker** [comment]
Tested open for business attribute, works fine.

**Comment by rightker** [comment]
Tested all instances mentioned in this issue. Everything works as expected. The time in the log being off earlier might be a DST problem, since this is the first time this has been tested since Phil fixed the password problem for Autodeployments AND we are now in DST. Need to try again in November. Closing this issue.
