### ISSUE TITLE
Couldn't create a process: sshexec.bat (But there is no sshexect.bat)

### ISSUE THREAD

**Issue by skulldah** [OpenMake-Software/DeployHub-Pro#180]
Hi everyone, 

We have a WebSphere Application Server deployment, we execute it for first time in 7.7 and show us this error.

![image001 2](https://cloud.githubusercontent.com/assets/1946648/22316820/4ec8a466-e335-11e6-9012-9305102a98a7.png)

We searched this bat, but we only find this: an sshexec.exe file 

![execbat](https://cloud.githubusercontent.com/assets/1946648/22316904/e9fa4a98-e335-11e6-89e3-4de829766708.jpg)

What we do is a work around, a .bat called sshexec.bat that calls sshexec.exe and pass all the parameters to that file.

Do you have a path to properly correct this issue.

Thank You.

**Comment by sbtaylor15** [comment]
Put these files in the lib directory and re-run the deployment.

[sshexec.zip](https://github.com/OpenMake-Software/ReleaseEngineer/files/733108/sshexec.zip)
