### ISSUE TITLE
using component throws error "not a valid component"

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#183]
The following code throws error "not a valid component".

using component 'DayOneComp' {
  echo ${component.name};
  deploy;
}

Works for component versions, just not for base components.

**Comment by pgibbs-openmake** [comment]
Suspect this is to do with the component not being uniquely named (i.e.: if there is another DayOneComp in the system a failure occurs). This should now correctly throw an AMBIGUOUS exception. Retest required.

**Comment by rightker** [comment]
Says "Could not find "CompName": Name is Ambiguous". Closing this issue.
