### ISSUE TITLE
getuser example doesn't acquire any useful data from the user object

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#191]
The simple set of commands in the online docs:

set user1 = getuser("User1");

A much better example, to show how getuser works, would be:

set user1 = getuser("admin");
echo "Telephone: ${user1.phone}";

**Comment by pgibbs-openmake** [comment]
Or echo the name with echo ${user1.name}

**Comment by rightker** [comment]
True, but I'd rather see something besides name, or maybe name and phone. So I thought I'd enter this into git to get your approval before changing the docs.

**Comment by rightker** [comment]
Put this into the online docs:

set user1 = getuser("admin");
echo "Name: ${user1.name}";
echo "Telephone: ${user1.phone}";

Closing this issue.
