### ISSUE TITLE
Cannot create calendar reservation when in sub-domain

### ISSUE THREAD

**Issue by pgibbs-openmake** [OpenMake-Software/DeployHub-Pro#199]
When a user's home domain is below GLOBAL then creating calendar entries can fail because the application/release drop-down list is not populated.

This is due to a bug in the internal permission model where if a parent domain is owned by a user outside of the calling user's domain hierarchy, the user lookup fails.

**Comment by rightker** [comment]
Tested, fixed, closing this issue.
