### ISSUE TITLE
Err Msg When Attempting to Add Change Request to Components and Apps 

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#203]
Err Msg 'Cannot connect to change request datasource: This is not a JSON Array.' appears when attempting to add a Change Request to an Application or Component. Change Request Datasources are set up correctly, and have been around for a while, and Components and Applications contain CRs that have been closed. This takes place in two different installations.

**Comment by pgibbs-openmake** [comment]
Need more information.
1) What is the datasource type (github, bugzilla, Jira)?
2) When does the message appear? When the + button is clicked? When the CRs are selected? When OK is clicked to add the selected CRs?

**Comment by rightker** [comment]
github, when clicking on the + button

**Comment by pgibbs-openmake** [comment]
What's the repository and product name?

**Comment by pgibbs-openmake** [comment]
For example:

https://api.github.com/repos/OpenMake-Software/DeployHub-Pro/issues/

Is not returning a JSON Array any more - this is causing the problem. Looks like they've changed the API.

**Comment by pgibbs-openmake** [comment]
Actually, ignore that. Trailing / was causing the issue. Without that, it works fine.

I added a new github repo datasource and added it to an app and + works fine. So I cannot reproduce right now. Can you try again, see if it was a blip at the github end?

**Comment by rightker** [comment]
I tried every possible combination and couldn't get it to work for this Repo:
https://github.com/OpenMake-Software/DeployHub-Pro/issues

So what exactly should I put into the Product and Repository fields? Should I use the one I've been using or the one you have shown above?

**Comment by pgibbs-openmake** [comment]
That's working fine for me both directly and via the api with DeployHub.

Call me!

**Comment by rightker** [comment]
Added Credential to Data Source and now it works. Github determined that there was too much activity from my particular i.p. address and was returning a null instead of a JSON array. Adding the Credential caused Github to think a different user was logging in and then returned the necessary data in the array. We need a better error msg for this, perhaps? Closing this issue.
