### ISSUE TITLE
Username and Password have been overwritten to "admin"

### ISSUE THREAD

**Issue by rraja002** [OpenMake-Software/DeployHub-Pro#210]
I am using chorme and when I enter user name and password it still reflecting admin.

![deployhub issue 2](https://user-images.githubusercontent.com/31516920/30136314-09f89bbc-9324-11e7-824b-463350499fb5.JPG)

**Comment by pgibbs-openmake** [comment]
Are you sure Chrome is not bringing up a list of previously used usernames and passwords? That could be the DeployHub "admin/admin" login that Chrome is inserting?

**Comment by sbtaylor15** [comment]
The yellow boxes mean that Chrome is filling it in for you.  Go ahead and type over the UserName and Password fields.  FYI, those fields are one way. That is from the UI to the DB.  We don't unencrypt them when you go back in and view the credential.  Both the username and password are encrypted not just the password.

**Comment by rraja002** [comment]
okay, I cleaned up chorme password and forms. now im not seeing that issue.
