### ISSUE TITLE
Disabled a Component Using Sourcery

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#213]
Create a Component and a Datasource, leaving the Datasource with default Type of bugzilla and Server URL Property of https://github.com/ (oops) -> Add the Datasource to the Component's Change Request Datasource field -> Try to use it and it throws an error -> Delete the Datasource since it won't let you change the Type once it's been saved -> Create another Datasource with the identical name and correct Server URL and Type -> Click on the Component, notice it locks up with "Load..." message. Refresh DeployHub and click on the Component, then General tab, notice it is blank where all of the fields should be.

**Comment by rightker** [comment]
Clicking on General tab for the Component shows blank screen, clicking on Endpoints and Build tab causes "Load..." lockup error.

**Comment by rightker** [comment]
Correction to the initial entry: Changed the Repository Property to https://github.com/, not the Server URL (which is still incorrect). Not that it makes any difference. I think it had to do with deleting a Datasource that belonged to a Component and then creating an identically named one (???)

**Comment by pgibbs-openmake** [comment]
I suspect deleting the datasource is what's causing the problem, not creating an identically named one afterward. We should prevent deletion if the datasource is being referenced from anywhere.

**Comment by pgibbs-openmake** [comment]
UPDATE: This is definitely causing the problem - we need to check that the datasource is not in use before it is allowed to be deleted.

**Comment by pgibbs-openmake** [comment]
Change applied to prevent a datasource from being deleted if it is in use. Rebuild and retest required.

**Comment by rightker** [comment]
Tested, works, closing this issue.

**Comment by rightker** [comment]
This is still a problem in Docker version 839.

**Comment by sbtaylor15** [comment]
Latest Build is 901 so you are probably still using an old version.

Steve Taylor
CITA and Co-Founder / OpenMake Software / tel: + 1.505.424.6439 x114 / mob:
+1.505.920.6106

Follow us on: Blog <https://www.openmakesoftware.com/insights/> / Twitter
<http://www.twitter.com/openmake>/ Facebook
<https://www.facebook.com/pages/OpenMake-Software/478045172208305> /
LinkedIn <https://www.linkedin.com/in/steve-taylor-b539205> / YouTube
<https://www.youtube.com/channel/UCSgF51hv2Qy88POFsA59uJQ>/ Google+
<https://plus.google.com/u/0/+Openmakesoftware>

*Winners of the Jolt Award in Change and Configuration Management*

**Comment by rightker** [comment]
Can I update it with curl -sL http://www.openmakesoftware.com/re/qa.html ?
