### ISSUE TITLE
Clicking Test Now Button on Status Tab Throws Connection Refused Error

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#223]
Created a new EndPoint -> Double checked that correct i.p address is used, correct Credential is being used with correct username and password -> Clicking Test Now Button on Status Tab Throws "Connection Refused" Error.

**Comment by pgibbs-openmake** [comment]
"Connection Refused" is a valid error and can occur if (a) you're connecting over SSH (SFTP) and the ssh server is not running on the target machine or (b) the ssh server is running but a firewall is preventing access. Neither issue implies a bug in DeployHub.

**Comment by rightker** [comment]
I can get in via putty and Steve says the ssh server is running.

**Comment by rightker** [comment]
I was using ftp instead of sftp. Closing this issue.
