### ISSUE TITLE
Deploying Demo App to Linux EndPoint Throws 'Plink' Error

### ISSUE THREAD

**Issue by rightker** [OpenMake-Software/DeployHub-Pro#224]
Log tab in Timeline tab shows an error concerning 'Plink'. Files were deployed.

![plinkerror](https://user-images.githubusercontent.com/14880152/32351172-2232ee72-bfe2-11e7-8b8e-52c45213140e.png)

**Comment by pgibbs-openmake** [comment]
Strange. I assume this is the Pro version? Could you check in C:\Program Files\Openmake Software\DeployHub\Engine\lib and confirm that there is a file called plink.exe in there?

**Comment by rightker** [comment]
Yes, there is.

**Comment by rightker** [comment]
If I run it by right clicking on it in the folder and selecting Run, it just appears for a second and disappears. Should it stay open?

**Comment by rightker** [comment]
Latest build includes a new sshexec.bat in C:\Program Files\Openmake Software\DeployHub\Engine\lib. Closing this issue.
