### ISSUE TITLE
DeployHub for Windows 10

### ISSUE THREAD

**Issue by alanromo** [OpenMake-Software/DeployHub-Pro#236]
Do you know if DeployHub will be supported for Windows 10 in the near future?
I have tried to install it on Windows 10 with all the prerequisites indicated for other windows versions, but I always get the message that there is another program missing. I guess this is because Windows 10 is not a supported platform.

**Comment by pgibbs-openmake** [comment]
DeployHub should work on Windows 10 without issue - I'm running it on a Windows 10 platform here and it's fine.

It's only supported on 64 bit. The latest installer includes everything including Postgres, Java and the ODBC drivers so there should be no need to install any pre-requisites. It's just a single MSI these days. Have you got the latest MSI installer?

**Comment by alanromo** [comment]
I got the msi which appears in the "Windows Installers" sections. Its size is 354,130 KB

**Comment by alanromo** [comment]
I just tried again.... and the same message:
There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor.

**Comment by pgibbs-openmake** [comment]
Did the installer open, prompt for port numbers etc and then fail with that message during the install procedure? Or did the MSI fail to open?

**Comment by alanromo** [comment]
It prompted for ports and other things. Then seems to be installing things, takes time, there is a screen with a bar moving... it seems that it will finish, but suddenly the message appears and everything is rolled back.

**Comment by pgibbs-openmake** [comment]
Okay, that implies the post-install application is failing to run.

After the install rolls back, are there any log files (such as install.log) left in the installation directory?

**Comment by pgibbs-openmake** [comment]
Could you also confirm your installation path? Are you accepting the default location or changing it? Are you specifying an install "for all users" or just the installing user?

**Comment by alanromo** [comment]
Regarding a install log... Unfortunately the installation directory is deleted when the roll back finishes. But if I take a look to the installation directory before the roll back starts... no, there is no a log file anywhere.
Regarding your other questions: 
Installation path is: C:\Program Files\Openmake Software\DeployHub\   (accepting default)
Web User Interface port: 8080
Postgres Database Port: 5439
Install for All Users

**Comment by alanromo** [comment]
By the way.... I just asked to someone else in my team to perform the same installation. She has a similar computer to the one that I'm using: same hardware (Thinkpad T470), same operating system (Windows 10 enterprise).
She gets the same error... same installation behavior

**Comment by pgibbs-openmake** [comment]
Well, if it's removing the install directory then that tells us that the post-install step is not running. If it *were* then it would create an install.log file and the directory would not be deleted when it rolls back. So the likelihood is that there's a dependent DLL missing somewhere

**Comment by pgibbs-openmake** [comment]
Let's try an administrative install - that should install the files without the post-install step. Then we can run the post-installer manually and see if it starts or reports a dependency failure.

To do this, open a DOS box and do an administrative install:

msiexec /a DeployHubOSS.msi

That should open a dialog box with fewer options (it'll just ask for an install directory). Just click through and let it install.

Then you should be able to navigate to C:\Program Files\Openmake Software\DeployHub\engine\bin

In there, there should be an executable called dpi.exe (that stands for DeployHub Post Install). That's what's run automatically during the install process to get everything setup. I'm thinking that is failing to start so just try double-clicking it. If it says "Stopped working" then that's expected (we didn't pass it any parameters) - if it doesn't start, Windows *should* report the DLL that's missing. We can take it from there.

Let me know how you get on.

**Comment by alanromo** [comment]
I get the message:
The installer has insufficient privileges to access this directory C:\Program Files\Openmake Software\DeployHub\
So, I tried in a personal directory. It installed things, but in the directory that you mention \Openmake Software\DeployHub\engine\bin... there are many things but the dpi.exe is not there. I see dm.exe, DeploymentManager.exe and setodbc.exe.... and many dll's

**Comment by pgibbs-openmake** [comment]
I think it's a hidden file. So you may need to go into your view options and select "Show Hidden Files". Then you should be able to see it. Or go into a DOS box, navigate to the directory and run dir /a

**Comment by alanromo** [comment]
OK, yes it's a hidden file. Once I ran it I got the following message:
The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.
When I go to the Windows application log I see the following message:
Activation context generation failed for "C:\personal\Openmake Software\Engine\bin\dpi.exe". Dependent Assembly Microsoft.VC90.MFC,processorArchitecture="amd64",publicKeyToken="1fc8b3b9a1e18e3b",type="win32",version="9.0.21022.8" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Comment by alanromo** [comment]
Taking a look to previous failed installations I found in the Windows application log this other error too:
Product: DeployHub Open Source Edition -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: _827E1C9F_1BF6_4CBE_B8AA_21E7F26128BB, location: C:\Program Files\Openmake Software\DeployHub\Engine\bin\dpi.exe, command: SERVER "C:\Program Files\Openmake Software\DeployHub\|0|5439|8080|1

...perhaps it might help

**Comment by pgibbs-openmake** [comment]
Brilliant, thanks. That first error message tells me what I need to know. It looks like a dependency on the C runtime libraries is not being fulfilled on your platform for some reason. This is odd because the C runtime ships with the installer and we've tested it on Windows 7, Windows 10 and Windows Server 2012 without issue.

Let's try installing the Microsoft Visual C++ 2008 Redistributable Package (x64) and see if that makes the problem go away. To do this just download the package from here:

https://www.microsoft.com/en-gb/download/details.aspx?id=15336

Download and install that package and then try and run the installer again. Let's see if that solves the issue.

**Comment by alanromo** [comment]
That fixed the problem.
Thanks a lot your your help!

**Comment by pgibbs-openmake** [comment]
Brilliant, thanks. We’ll take a look at getting that fixed in the installer.
